name: Deploy PR to Connect as a temporary app
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy the PR to RStudio Connect
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Publish the PR
        uses: rstudio/actions/connect-publish@main
        with:
          url: http://ec2-18-221-78-109.us-east-2.compute.amazonaws.com/rsconnect/
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: all
          show-logs: true
          # for more on app identifiers or multiple app deployments, see
          # https://github.com/rstudio/actions/tree/main/connect-publish#dir
          dir: |
            ./:/pr/shinytest-example-app/${{ github.head_ref }}
